# Generated by Django 5.1 on 2024-08-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookRecommender", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="book",
            name="description",
        ),
    ]
